### ISSUE TITLE
Worth approaching Setapp?

### ISSUE THREAD

**Issue by neeklamy** [rurza/NepTunes#12]
Maybe you’ve already heard of it, but there’s this new subscription service for Mac applications: [Setapp](https://setapp.com/).

Setapp’s MO is to offer a small selection of well crafted applications, NepTunes would be a great fit!

There’s possibly two issues however that you’d need to discuss with the Setapp owners:

1. **They aren’t currently accepting open source applications.** There’s no official word on why this should be, I asked them and they said about Setapp being for paid for apps, but they seem open to the idea of including open source apps.
2. **Payments.** Setapp pays out based on customer usage. I haven’t combed through all of the apps that they have, but I don’t know how a Dock-less app that runs all the time would figure into their calculations. But then they have the backup app, ChronoSync Express which must always be running in the background.

**Comment by rurza** [comment]
I heard about Setapp before and I already sent them a request. The answer, I've received on March, the 28th:

> Hello Adam,

>I hope all is well.

(...)
>As for Neptunes, I've received some great feedback; however, the decision has been put on hold until the end of May.

>We appreciate your time and will be in touch in two months.

>Thank you!

**Comment by rurza** [comment]
> One other thought, what if you had a closed-source fork of the project?

They didn't told me that they have a problem with NepTunes being open source.

> If a NepTunes fork could replace iTunes for day-to-day audio playback, then that’d be great. There needs to be some decent iTunes competition.

NepTunes is a last.fm scrobbler + minimalistic controller for iTunes/Spotify. Period. Making music player based on NepTunes is like making a car from bicycle pedal. But if someone want to try - she/he will got my blessing. Sure, iTunes isn't great (well, it sucks) but with every update it's better IMO. More important to me is that iTunes is Apple Music client. New NepTunes aka music-player-for-mac can't support it – there is no official way to stream music from Apple Music. But I will continue investing my time in NepTunes in its actual format.
I'm struggling to make a decent scrobbler for iOS (mostly because limitation of background APIs and App Store policy) and that's one of my priorities. Right now I'm working on Background for iPhone which is a Unsplash client. Also I have a idea to make nice, easy-to-use Twitter client (I'm not happy with Tweetbot).  But I don't have enough spare time :(
