### ISSUE TITLE
[Request] Automatically Open when iTunes start

### ISSUE THREAD

**Issue by Bilalh** [rurza/NepTunes#2]
Automatically opening NepTunes when iTunes start, would be a nice addition.

**Comment by Zifius** [comment]
:+1: Will try to work on a PR for this once I sort the scrobbling itself

**Comment by rurza** [comment]
I'm not going to implement it because it doesn't make sense for NepTunes.
Why?
To automatically open app when iTunes I need another helper app to watch iTunes... ;) Just add NepTunes to Login Items in System Preferences. 

<img width="780" alt="screen shot 2015-07-06 at 21 38 29" src="https://cloud.githubusercontent.com/assets/2467137/8531398/5c56d6bc-2427-11e5-97e6-0fd88014b6b7.png">

**Comment by Bilalh** [comment]
That works just as well, thanks

**Comment by Zifius** [comment]
You are totally right @rurza, I realized that as far as the official scrobbler installs an iTunes plugin and then it makes it really hard time when you want to disable the launching: "Please close the app now"... So :thumbs up: for keeping it clean
